PROJECT_NAME: "padim"
EXP_NAME: "padim-folder"
SEED: 42
DEVICE: "cpu"
TASK: "classification"

MODEL:
  BACKBONE: "wide_resnet50_2"
  RETURN_NODES: ["layer1.2.relu_2", "layer2.3.relu_2", "layer3.3.relu_2"]

DATASETS:
  ROOT:
    TRAIN: "./data/folder/train"
    TEST: "./data/folder/test"
  TRANSFORMS:
    RESIZE:
      HEIGHT: 224
      WIDTH: 224
    CENTER_CROP:
      HEIGHT: 224
      WIDTH: 224
    NORMALIZE:
      MEAN: [ 0.485, 0.456, 0.406 ]
      STD: [ 0.229, 0.224, 0.225 ]

TRAIN:
  HYP:
    IMGS_PER_BATCH: 32

  PRINT_FREQ: 1

VAL:
  WEIGHTS_PATH: "./results/train/padim-folder/model.pkl"

  HYP:
    IMGS_PER_BATCH: 32

  PRINT_FREQ: 1