PROJECT_NAME: "padim"
EXP_NAME: "padim-mvtec"
SEED: 42
DEVICE: "cpu"
TASK: "classification"

MODEL:
  BACKBONE: "resnet18"
  RETURN_NODES: ["layer1.1.relu_1", "layer2.1.relu_1", "layer3.1.relu_1"]

DATASETS:
  ROOT:
    TRAIN: "./data/folder/train"
    TEST: "./data/folder/test"
  TRANSFORMS:
    RESIZE: 256
    CENTER_CROP: 224

TRAIN:
  HYP:
    IMGS_PER_BATCH: 32

VAL:
  WEIGHTS_PATH: "./results/train/padim-mvtec/bottle.pkl"

  HYP:
    IMGS_PER_BATCH: 32