PROJECT_NAME: "padim"
EXP_NAME: "padim-mvtec_bottle"
SEED: 42
DEVICE: "cuda"
TASK: "segmentation"

MODEL:
  BACKBONE: "resnet18"
  RETURN_NODES: ["layer1.1.relu_1", "layer2.1.relu_1", "layer3.1.relu_1"]

DATASETS:
  ROOT: "./data/mvtec_anomaly_detection"
  CATEGORY: "bottle"
  TRANSFORMS:
    RESIZE: 256
    CENTER_CROP: 224

TRAIN:
  HYP:
    IMGS_PER_BATCH: 32

VAL:
  WEIGHTS_PATH: "./results/train/padim-mvtec_bottle/model.pkl"

  HYP:
    IMGS_PER_BATCH: 32