PROJECT_NAME: "padim"
EXP_NAME: "padim-folder"
SEED: 42
DEVICE: "cpu"
TASK: "classification"

MODEL:
  BACKBONE: "resnet18"
  RETURN_NODES: ["layer1.1.relu_1", "layer2.1.relu_1", "layer3.1.relu_1"]

DATASETS:
  ROOT:
    TRAIN: "./data/folder/train"
    TEST: "./data/folder/test"
  TRANSFORMS:
    RESIZE:
      HEIGHT: 256
      WIDTH: 256
    CENTER_CROP:
      HEIGHT: 224
      WIDTH: 224
    NORMALIZE:
      MEAN: [ 0.485, 0.456, 0.406 ]
      STD: [ 0.229, 0.224, 0.225 ]

TRAIN:
  HYP:
    IMGS_PER_BATCH: 32

  PRINT_FREQ: 1

VAL:
  WEIGHTS_PATH: "./results/train/padim-folder/model.pkl"