PROJECT_NAME: "padim"
EXP_NAME: "padim-mvtec"
SEED: 42
DEVICE: "cpu"

MODEL:
  BACKBONE: "resnet18"
  RETURN_NODES: ["layer1.1.relu_1", "layer2.1.relu_1", "layer3.1.relu_1"]

DATASETS:
  ROOT: "./data/mvtec_anomaly_detection"
  CATEGORY: "bottle"

TRAIN:
  HYP:
    IMGS_PER_BATCH: 32

VAL:
  WEIGHTS_PATH: "./results/train/padim-mvtec/bottle.pkl"

  HYP:
    IMGS_PER_BATCH: 1